export enum EventTypes{
    GET_ROUTER_RTP_CAPABILITIES="GET_ROUTER_RTP_CAPABILITIES",
    CREATE_WEBRTC_TRANSPORT="CREATE_WEBRTC_TRANSPORT",
    CONNECT_TRANSPORT="CONNECT_TRANSPORT",
    PRODUCE="PRODUCE",
    CONSUME="CONSUME",
    GET_PRODUCERS="GET_PRODUCERS",
    CANNOT_CONSUME="CANNOT_CONSUME",
    //client
    WELCOME="WELCOME",
    ROUTER_RTP_CAPABILITIES="ROUTER_RTP_CAPABILITIES",
    WEBRTC_TRANSPORT_CREATED="WEBRTC_TRANSPORT_CREATED",
    TRANSPORT_CONNECTED="TRANSPORT_CONNECTED",
    PRODUCED="PRODUCED",
    CONSUMED="CONSUMED",
    PRODUCERS="PRODUCERS",
    NEW_PRODUCER="NEW_PRODUCER",
    PEER_CLOSED="PEER_CLOSED",
    ERROR='ERROR',
    PRODUCER_CLOSED='PRODUCER_CLOSED',
    RESUME_PAUSED_CONSUMER="RESUME_PAUSED_CONSUMER",
    CONNECT_CONSUMER_TRANSPORT="CONNECT_CONSUMER_TRANSPORT",
    CONNECT_PRODUCER_TRANSPORT="CONNECT_PRODUCER_TRANSPORT",
    RESUME_CONSUMER="RESUME_CONSUMER",
    PEER_DISCONNECTED="PEER_DISCONNECTED",
    PRODUCER_CLOSED_NOTIFICATION="PRODUCER_CLOSED_NOTIFICATION"

}